image: node:16-alpine

cache:
  paths:
    - node_modules/

stages:
  - install
  # - test
  - deploy

Install:
  stage: install
  tags:
    - node
  before_script:
    - npm install
  script:
    - npm run build

# Test:
#   stage: test
#   script:
#    - npm test

Deploy to UAT:
  image: ruby:3.1.1
  stage: connect
  tags:
    - node
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - export NODE_OPTIONS=--max_old_space_size=4096
  only:
    - uat
  environment:
    name: uat
    url: $HEROKU_APP_HOST

after_script:
  - echo "UAT Web Application Deployed"


