image: node:16-alpine

cache:
  paths:
    - node_modules/

stages:
  - install
  # - test
  - deploy

Install:
  stage: install
  script:
    - npm install

# Test:
#   stage: test
#   script:
#    - npm test

Production:
  image: ruby:3.1.1
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - export NODE_OPTIONS=--max_old_space_size=4096
  only:
    - master
  environment:
    name: production
    url: $HEROKU_APP_HOST

after_script:
  - echo "Application Deployed"
