image: node:16-alpine

cache:
  paths:
    - node_modules/

stages:
  - install

install:
  stage: install
  tags:
    - general-docker
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      -
after_script:
  - echo "React application has been successfully build"


