image: node:16-alpine

cache:
  paths:
    - node_modules/

stages:
  - install
  - deploy

install:
  stage: install
  tags:
    - general-docker
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

deploy-to-uat:
  image: ruby:3.1.1
  stage: deploy
  tags:
    - general-docker
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - export NODE_OPTIONS=--max_old_space_size=4096
  after_script:
    - echo "UAT Web Application Deployed"
  only:
    - uat
  environment:
    name: uat
    url: $HEROKU_APP_HOST



